// <auto-generated />
using System;
using Accounting.DataAccess;
using Accounting.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Accounting.Migrations
{
    [DbContext(typeof(AccountingDbContext))]
    [Migration("20210624223950_SeeSetters")]
    partial class SeeSetters
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Accounting.Domain.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DisplayPosition")
                        .HasColumnType("int");

                    b.Property<int>("Group")
                        .HasColumnType("int");

                    b.Property<int>("Grouping")
                        .HasColumnType("int");

                    b.Property<int>("HaveSet")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrivateSet")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasDiscriminator<int>("Grouping");
                });

            modelBuilder.Entity("Accounting.Domain.HeadingAccount", b =>
                {
                    b.HasBaseType("Accounting.Domain.Account");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Accounting.Domain.PostingAccount", b =>
                {
                    b.HasBaseType("Accounting.Domain.Account");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("Accounting.Domain.RootAccount", b =>
                {
                    b.HasBaseType("Accounting.Domain.Account");

                    b.HasDiscriminator().HasValue(1);
                });
#pragma warning restore 612, 618
        }
    }
}
